# Generated by Django 5.2.7 on 2025-10-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_level', models.CharField(default='safe', max_length=20)),
                ('flags', models.TextField(blank=True, null=True)),
                ('date_checked', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspicious Link',
                'verbose_name_plural': 'Suspicious Links',
                'ordering': ['-date_checked'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_level', models.CharField(default='safe', max_length=20)),
                ('flags', models.TextField(blank=True, null=True)),
                ('date_checked', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspicious Message',
                'verbose_name_plural': 'Suspicious Messages',
                'ordering': ['-date_checked'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_checks', models.IntegerField(default=0)),
                ('threats_detected', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
