# Generated by Django 5.2.7 on 2025-10-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishield', '0002_userprofile_email_verification_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
