# Generated by Django 5.2.7 on 2025-10-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishield', '0003_alter_userprofile_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_sent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_scan_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_security_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Administrator'), ('security_analyst', 'Security Analyst')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_tips',
            field=models.BooleanField(default=True),
        ),
    ]
